name: Python Tests

on:
  push:
    branches: [ experimental ]
  pull_request:
    branches: [ experimental ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt

    - name: Run tests
      run: |
        pytest --html=report.html --self-contained-html
    
    - name: Rename report.html to index.html
      run: |
        mv report.html index.html

    - name: Upload HTML test report artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: index.html

    - name: Deploy report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        publish_branch: gh-pages
